#!/bin/bash
set -euo pipefail

VM_DIR="${OXBOW_AE_VM_DIR:-$HOME/oxbow/oxbow-ae-vm}"
VM_USER="oxbow"
SSH_PORT="5555"
ROOT_SIZE="${OXBOW_VM_ROOT_SIZE:-20G}"
NVME_SIZE="${OXBOW_VM_NVME_SIZE:-20G}"
QEMU_CPUS="${OXBOW_VM_CPUS:-16}"
QEMU_MEM="${OXBOW_VM_MEM:-24G}"
IMAGE_URL="${OXBOW_VM_IMAGE_URL:-https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img}"
FORCE=0

print_usage() {
	echo "Usage: $(basename "$0") [--dir <vm_dir>] [--force]"
}

while [ $# -gt 0 ]; do
	case "$1" in
	--dir)
		VM_DIR="$2"
		shift 2
		;;
	--force)
		FORCE=1
		shift
		;;
	-h | --help)
		print_usage
		exit 0
		;;
	*)
		print_usage
		exit 2
		;;
	esac
done

need_cmd() {
	if ! command -v "$1" >/dev/null 2>&1; then
		echo "Missing command: $1"
		exit 1
	fi
}

download_file() {
	local url="$1"
	local out="$2"

	if command -v curl >/dev/null 2>&1; then
		curl -L -o "$out" "$url"
	elif command -v wget >/dev/null 2>&1; then
		wget -O "$out" "$url"
	else
		echo "Install curl or wget to download the Ubuntu cloud image."
		exit 1
	fi
}

write_env() {
	printf "%s=%q\n" "$1" "$2"
}

need_cmd qemu-img
need_cmd cloud-localds
need_cmd ssh-keygen

VM_DIR="${VM_DIR%/}"
BASE_IMG="$VM_DIR/jammy-server-cloudimg-amd64.img"
ROOT_IMG="$VM_DIR/oxbow-ae-root.qcow2"
NVME_SECURE_IMG="$VM_DIR/nvme-secure.raw"
NVME_DEVFS_IMG="$VM_DIR/nvme-devfs.raw"
SEED_ISO="$VM_DIR/seed.iso"
SSH_DIR="$VM_DIR/ssh"
SSH_KEY="$SSH_DIR/oxbow-ae"
USER_DATA="$VM_DIR/user-data"
META_DATA="$VM_DIR/meta-data"
VM_ENV="$VM_DIR/vm.env"

if [ "$FORCE" -eq 1 ]; then
	rm -f "$ROOT_IMG" "$NVME_SECURE_IMG" "$NVME_DEVFS_IMG" "$SEED_ISO" \
		"$USER_DATA" "$META_DATA" "$VM_ENV" \
		"$VM_DIR/known_hosts" "$VM_DIR/qemu.pid" "$VM_DIR/qemu-serial.log"
else
	for f in "$ROOT_IMG" "$NVME_SECURE_IMG" "$NVME_DEVFS_IMG" "$SEED_ISO" "$VM_ENV"; do
		if [ -e "$f" ]; then
			echo "$f already exists. Use --force to recreate VM images."
			exit 1
		fi
	done
fi

mkdir -p "$VM_DIR" "$SSH_DIR"

if [ ! -f "$BASE_IMG" ]; then
	echo "Downloading Ubuntu cloud image..."
	download_file "$IMAGE_URL" "$BASE_IMG"
fi

if [ ! -f "$SSH_KEY" ]; then
	ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -C "oxbow-ae-vm"
fi

if [ ! -f "$SSH_KEY.pub" ]; then
	ssh-keygen -y -f "$SSH_KEY" >"$SSH_KEY.pub"
fi

SSH_PUB_KEY=$(cat "$SSH_KEY.pub")

cat >"$USER_DATA" <<EOF
#cloud-config
users:
  - name: $VM_USER
    groups: [sudo]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - $SSH_PUB_KEY
ssh_pwauth: false
disable_root: true
package_update: true
packages:
  - openssh-server
  - rsync
  - build-essential
  - cmake
  - git
  - libacl1-dev
  - libcapstone-dev
  - nvme-cli
  - pciutils
  - pkg-config
  - python3
  - python3-pip
  - re2c
runcmd:
  - [ mkdir, -p, /home/$VM_USER/oxbow.code ]
  - [ chown, -R, $VM_USER:$VM_USER, /home/$VM_USER/oxbow.code ]
EOF

cat >"$META_DATA" <<EOF
instance-id: oxbow-ae-vm
local-hostname: oxbow-ae-vm
EOF

cloud-localds "$SEED_ISO" "$USER_DATA" "$META_DATA"

qemu-img create -f qcow2 -F qcow2 -b "$BASE_IMG" "$ROOT_IMG" "$ROOT_SIZE"
qemu-img create -f raw "$NVME_SECURE_IMG" "$NVME_SIZE"
qemu-img create -f raw "$NVME_DEVFS_IMG" "$NVME_SIZE"

{
	echo "# Generated by tools/qemu/create_vm.sh"
	write_env VM_DIR "$VM_DIR"
	write_env VM_USER "$VM_USER"
	write_env SSH_PORT "$SSH_PORT"
	write_env ROOT_IMG "$ROOT_IMG"
	write_env SEED_ISO "$SEED_ISO"
	write_env SSH_KEY "$SSH_KEY"
	write_env NVME_SECURE_IMG "$NVME_SECURE_IMG"
	write_env NVME_DEVFS_IMG "$NVME_DEVFS_IMG"
	write_env SECURE_NVME_SERIAL "oxbow-secure"
	write_env DEVFS_NVME_SERIAL "oxbow-devfs"
	write_env QEMU_CPUS "$QEMU_CPUS"
	write_env QEMU_MEM "$QEMU_MEM"
} >"$VM_ENV"

echo "VM files are created in $VM_DIR"
