#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)

SECURE_SERIAL="oxbow-secure"
DEVFS_SERIAL="oxbow-devfs"
SECURE_BDF=""
DEVFS_BDF=""
YES=0

print_usage() {
	echo "Usage: $(basename "$0") [--yes]
       $(basename "$0") [--secure-bdf <bdf>] [--devfs-bdf <bdf>] [--yes]"
}

while [ $# -gt 0 ]; do
	case "$1" in
	--yes)
		YES=1
		shift
		;;
	--secure-bdf)
		SECURE_BDF="$2"
		shift 2
		;;
	--devfs-bdf)
		DEVFS_BDF="$2"
		shift 2
		;;
	-h | --help)
		print_usage
		exit 0
		;;
	*)
		print_usage
		exit 2
		;;
	esac
done

need_cmd() {
	if ! command -v "$1" >/dev/null 2>&1; then
		echo "Missing command: $1"
		exit 1
	fi
}

find_bdf_by_serial() {
	local wanted="$1"
	local serial

	for ctrl_path in /sys/class/nvme/nvme*; do
		[ -e "$ctrl_path/serial" ] || continue
		serial=$(tr -d '[:space:]' <"$ctrl_path/serial")
		if [ "$serial" = "$wanted" ]; then
			basename "$(readlink -f "$ctrl_path/device")"
			return 0
		fi
	done

	return 1
}

replace_host_journaling() {
	local file="$1"

	perl -0pi -e 's@(?m)^\s*//\s*#define\s+HOST_JOURNALING\b.*$@#define HOST_JOURNALING // Run DevFS on the host.@' "$file"
	if ! grep -Eq '^[[:space:]]*#define[[:space:]]+HOST_JOURNALING\b' "$file"; then
		perl -0pi -e 's@(?m)^#ifdef HOST_JOURNALING@#define HOST_JOURNALING // Run DevFS on the host.\n#ifdef HOST_JOURNALING@' "$file"
	fi
}

replace_pin_mode() {
	local file="$1"

	perl -0pi -e 's@(?m)^#define[[:space:]]+OXB_PIN_MODE[[:space:]]+OXB_PIN_MODE_[A-Z0-9_]+@#define OXB_PIN_MODE OXB_PIN_MODE_NUMA0_ONLY@' "$file"
}

replace_mkfs_layout() {
	local file="$1"

	perl -0pi -e '
		s@(?m)^(#define[[:space:]]+EXT4_TOTAL_PARTITION_SIZE\b.*)$@// $1@g;
		s@(?m)^(#define[[:space:]]+EXT4_NR_JOURNAL_BLOCKS\b.*)$@// $1@g;
		s@(?m)^//[[:space:]]*#define[[:space:]]+EXT4_TOTAL_PARTITION_SIZE[^\n]*// VM[^\n]*$@#define EXT4_TOTAL_PARTITION_SIZE (18UL * 1024 * 1024 * 1024) // 18GB total. // VM: 12GB filesystem + 3GB journal + 3GB staging.@g;
		s@(?m)^//[[:space:]]*#define[[:space:]]+EXT4_NR_JOURNAL_BLOCKS[^\n]*// VM[^\n]*$@#define EXT4_NR_JOURNAL_BLOCKS ((3UL * 1024 * 1024 * 1024) / 4096) // 3 GB of journal. // VM@g;
	' "$file"

	if [ "$(grep -Ec '^[[:space:]]*#define[[:space:]]+EXT4_TOTAL_PARTITION_SIZE\b' "$file")" -ne 1 ]; then
		echo "Failed to set EXT4_TOTAL_PARTITION_SIZE in $file"
		exit 1
	fi

	if [ "$(grep -Ec '^[[:space:]]*#define[[:space:]]+EXT4_NR_JOURNAL_BLOCKS\b' "$file")" -ne 1 ]; then
		echo "Failed to set EXT4_NR_JOURNAL_BLOCKS in $file"
		exit 1
	fi
}

enable_secure_daemon_msg_ring() {
	local file="$1"

	perl -0pi -e 's@(?m)^([[:space:]]*)#[[:space:]]*'\''-DOXBOW_IPC_MSG_RING'\'',@$1'\''-DOXBOW_IPC_MSG_RING'\'',@' "$file"
	if ! grep -Eq "^[[:space:]]*'-DOXBOW_IPC_MSG_RING'," "$file"; then
		echo "Failed to enable OXBOW_IPC_MSG_RING in $file"
		exit 1
	fi
}

need_cmd perl

if [ -z "$SECURE_BDF" ]; then
	SECURE_BDF=$(find_bdf_by_serial "$SECURE_SERIAL") || {
		echo "Cannot find QEMU NVMe controller with serial $SECURE_SERIAL"
		echo "If the device is already bound to SPDK, reset it first or pass --secure-bdf."
		exit 1
	}
fi

if [ -z "$DEVFS_BDF" ]; then
	DEVFS_BDF=$(find_bdf_by_serial "$DEVFS_SERIAL") || {
		echo "Cannot find QEMU NVMe controller with serial $DEVFS_SERIAL"
		echo "If the device is already bound to SPDK, reset it first or pass --devfs-bdf."
		exit 1
	}
fi

cat <<EOF
This will apply VM-only Oxbow configuration in:
  $REPO_ROOT

Tracked files modified in this checkout:
  oxbow/devfs/include/common/oxbow.h
  oxbow/devfs/include/common/cpu_pinning.h
  oxbow/secure_daemon/meson.build
  oxbow/secure_daemon/src/fs/lwext4/ext4_mkfs.c

Untracked local files generated:
  oxbow/secure_daemon/myconf.sh
  oxbow/devfs/myconf.sh

Secure Daemon BDF: $SECURE_BDF
DevFS BDF:         $DEVFS_BDF
EOF

if [ "$YES" -ne 1 ]; then
	read -r -p "Type 'yes' to continue: " ans
	if [ "$ans" != "yes" ]; then
		echo "Abort."
		exit 1
	fi
fi

replace_host_journaling "$REPO_ROOT/oxbow/devfs/include/common/oxbow.h"
replace_pin_mode "$REPO_ROOT/oxbow/devfs/include/common/cpu_pinning.h"
enable_secure_daemon_msg_ring "$REPO_ROOT/oxbow/secure_daemon/meson.build"
replace_mkfs_layout "$REPO_ROOT/oxbow/secure_daemon/src/fs/lwext4/ext4_mkfs.c"

cat >"$REPO_ROOT/oxbow/secure_daemon/myconf.sh" <<EOF
#!/bin/bash
# Generated by tools/qemu/setup_vm_guest.sh.
export pcie_nvme_addr="$SECURE_BDF"
export rpc_rdma_thread_num=1
export rpc_shmem_thread_num=1
export io_handler_thread_num=1
export snapshot_thread_num=1
export storage_engine_thread_num=1
export read_worker_thread_num=2
EOF

cat >"$REPO_ROOT/oxbow/devfs/myconf.sh" <<EOF
#!/bin/bash
# Generated by tools/qemu/setup_vm_guest.sh.
export pcie_nvme_addr="$DEVFS_BDF"
export rpc_thread_num=4
EOF

chmod +x "$REPO_ROOT/oxbow/secure_daemon/myconf.sh" "$REPO_ROOT/oxbow/devfs/myconf.sh"

sudo mkdir -p /mnt/oxbow_flag
sudo chmod 777 /mnt/oxbow_flag

echo "VM guest configuration is applied."
